version: '3.6'
services:
  postgres:
    image: postgres
    container_name: mypostgres
    restart: always
    environment:
      POSTGRES_DB: world
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pra123
    volumes:
      - db_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine
    container_name: myhasura
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:pra123@mypostgres:5432/world
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey34232d1


  serverless-offline:
    image: node:20
    container_name: myserverlesscontainer
    working_dir: /new_hasura_project
    ports:
      - "3000:3000"
      - "3002:3002"
    command: bash -c "npx serverless offline --host 0.0.0.0"
    volumes:
      - .:/new_hasura_project



networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:


#temporal
